version: '3.8'

services:
  mysql-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: clinicDB2
      MYSQL_ROOT_PASSWORD: Ah123456789Ah
    ports:
      - "3307:3306"

  golang-backend:
    build:
      context: .
      dockerfile: Dockerfile.golang
    environment:
      DB_HOST: "mysql-database"
      PORT: "3307"
      USER: "root"
      PASSWORD: "Ah123456789Ah"
      DB_NAME: "clinicDB2"
    ports:
      - "8081:8081"
    depends_on:
      - mysql-database

  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - golang-backend