FROM golang:1.21

WORKDIR /app

COPY go.mod go.sum ./golang-backend/

ENV DB_HOST="dbcontainer"
ENV PORT="3306"
ENV USER="root"
ENV PASSWORD="Ah123456789Ah"
ENV DB_NAME="clinicDB2"

RUN go build -o /bin .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping


CMD [ "/docker-gs-ping" ]