version: '3.8'

services:
  mysql-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: clinicDB2
      MYSQL_ROOT_PASSWORD: Ah123456789Ah
    ports:
      - "3308:3306"  # Exposing MySQL on port 3308 for host access

  golang-backend:
    build:
      context: .
      dockerfile: Dockerfile.golang
    environment:
      DB_HOST: "mysql-database"
      PORT: "3306"  # Internal MySQL port
      USER: "root"
      PASSWORD: "Ah123456789Ah"
      DB_NAME: "clinicDB2"
      START_DELAY: "10"  # Delay in seconds
    ports:
      - "8081:8081"
    depends_on:
      - mysql-database

  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - golang-backend
