FROM golang:latest
RUN mkdir /app
WORKDIR /app

USER root
COPY ./golang-backend .

ENV DB_HOST="mysql-db"
ENV PORT="3306"
ENV USER="root"
ENV PASSWORD="Ah123456789Ah"
ENV DB_NAME="clinicDB2"

RUN go build -o /bin .
RUN go mod download


EXPOSE 8081

CMD [ "go","run","."]
