FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./react-frontend .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# docker run --name react -p 3000:3000 frontend
